#!/command/with-contenv bash

echo "Starting Nautobot Server"
export PATH=$S6_GLOBAL_PATH
s6-setuidgid nautobot nautobot-server start --ini /opt/nautobot/uwsgi.ini 2>&1 | while read line ; do
  echo "nautobot-server: $line"
  if [[ $line == "spawned uWSGI http 1"* ]] ; then
    echo "nautobot-server: Server is ONLINE!"
    echo >&3
  fi
done
