# We can't remove volumes in a compose override, for the test configuration using the final containers
# we don't want the volumes so this is the default override file to add the volumes in the dev case
# any override will need to include these volumes to use them.
# see:  https://github.com/docker/compose/issues/3729
---
version: "3.4"
services:
  db:
    image: "postgres:13-alpine"
    env_file:
      - ".env"
    volumes:
      - "db_data:/var/lib/postgresql/data"
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - ".env"
  nautobot:
    image: "abates-nautobot"
    ports: 
      - "8080:8080"
    env_file:
      - ".env"
    volumes:
      - "./plugin_config.py:/opt/nautobot/plugin_config.py"
      - "./plugin_requirements.txt:/opt/nautobot/plugin_requirements.txt"
      - "nautobot_data:/var/lib/nautobot"
    depends_on:
      - "db"
      - "redis"
volumes:
  db_data: {}
  nautobot_data: {}
