---
version: "3.8"
services:
  nautobot:
    build:
      target: "nautobot"
    image: "${BASE_IMAGE}:${BASE_TAG}"
    ports:
      - "8080:8080"
      - "8443:8443"
    env_file:
      - "./production.env"
      - "./creds.env"
  worker:
    image: "${BASE_IMAGE}:${BASE_TAG}"
    env_file:
      - "./production.env"
      - "./creds.env"
