name: Create and publish a Docker image

on:
  push:
    branches: ["main"]

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  build-and-push-image:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - name: "Chekout repository"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v4"
      - name: "Extract Versions"
        run: |
          echo "GITTHUB_NAUTOBOT_VERSION=$(poetry show nautobot | grep 'version' | awk '{print $3}')" >> $GITHUB_ENV
          echo "GITHUB_PROJECT_VERSION=$(poetry version -s)" >> $GITHUB_ENV
          echo "GITHUB_NEW_TAG=v$(poetry version -s)" >> $GITHUB_ENV
          echo "GITHUB_LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      - name: "Validate Tag"
        if: "${{ env.GITHUB_PROJECT_VERSION == env.GITHUB_LATEST_TAG }}"
        uses: "actions/github-script@v3"
        with:
          script: "core.setFailed('Project version number and latest tag are the same')"

      - name: "Validate Version Numbers"
        if: "${{ GITHUB_NAUTOBOT_VERSION != GITHUB_PROJECT_VERSION }}"
        uses: "actions/github-script@v3"
        with:
          script: "core.setFailed('Project version number and Nautobot version number differ')"
      - name: "Add Tag"
        run: |
          git config --global user.name "Andrew Bates"
          git config --global user.email "358901+abates@users.noreply.github.com"
          git tag -a $GITHUB_NEW_TAG -m "Version $GITHUB_PROJECT_VERSION"
          git push origin $GITHUB_NEW_TAG

