name: Create and publish a Docker image

on:
  push:
    branches: ["main"]

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  tag-main-branch:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      packages: "write"
    steps:
      - name: "Chekout repository"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v4"
      - name: "Extract Versions"
        run: |
          echo "GITHUB_NAUTOBOT_VERSION=$(poetry show nautobot | grep 'version' | awk '{print $3}')" >> $GITHUB_ENV
          echo "GITHUB_PROJECT_VERSION=$(poetry version -s)" >> $GITHUB_ENV
          echo "GITHUB_NEW_TAG=v$(poetry version -s)" >> $GITHUB_ENV
          echo "GITHUB_LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo)" >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: "Add Tag"
        if: "${{ env.GITHUB_PROJECT_VERSION != env.GITHUB_LATEST_TAG && env.GITHUB_NAUTOBOT_VERSION == env.GITHUB_PROJECT_VERSION }}"
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag "$GITHUB_NEW_TAG"
          git push origin $GITHUB_NEW_TAG

